name: rick_and_morty
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  bloc_concurrency: ^0.2.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  http: ^0.13.5
  json_annotation: ^4.7.0
  stream_transform: ^2.0.0

dev_dependencies:
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.4.0

flutter:

  uses-material-design: true

  assets:
    - images/logo.png
    - images/logo2.png
    - images/logo3.png
    - images/rick_image.png
